services:
  backend:
    build: ./backend
    ports:
      - "8003:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8003
    depends_on:
      - backend
